import hdf5plugin
import h5py
import numpy as np
from CosCalNL_multi import readgadget

class Base(object):
    def __init__(self, BoxSize = 1000, NMesh = 512, *args, **kwargs):
        super(Base, self).__init__()
        """
        Define the basic variable
        """
        self.BoxSize = BoxSize
        self.NMesh = NMesh
        self.ParameterSet()
        
    def GetDensity(self):
        """
        Return the density field 1+delta
        """
        return self.deltaX + 1
    
    def GetPosition(self):
        """
        Return the position of particles
        """
        return self.Position
    
    def GetPosition0(self):
        """
        Return the origin position
        """
        return self.Position0
        
    def GetRecDensity(self):
        """
        Return the estimated density field
        """
        return self.deltaX0 + 1
    
    def GetDis(self):
        """
        Return the displacement field
        """
        temp = np.empty([self.NMesh, self.NMesh, self.NMesh, 3])
        temp[:, :, :, 0] = self.dx
        temp[:, :, :, 1] = self.dy
        temp[:, :, :, 2] = self.dz
        return temp
        
    def ParameterSet(self):
        """
        Set Parameters 
        """
        # Calculate Mesh Size
        self.H = self.BoxSize/self.NMesh
        # Wave Number Parameters
        self.fn = np.fft.fftfreq(self.NMesh, 1. / self.NMesh).astype(np.float32)
        self.rfn = np.fft.rfftfreq(self.NMesh, 1. / self.NMesh).astype(np.float32)
        self.fnx = (self.fn[:, None, None]
                  + np.zeros(self.NMesh, dtype = np.float32)[None, :, None]
                  + np.zeros(int(self.NMesh/2 + 1), dtype = np.float32)[None, None, :])
        self.fny = (np.zeros(self.NMesh, dtype = np.float32)[:, None, None]
                  + self.fn[None, :, None] 
                  + np.zeros(int(self.NMesh/2 + 1), dtype = np.float32)[None, None, :])
        self.fnz = (np.zeros(self.NMesh, dtype = np.float32)[:, None, None]
                  + np.zeros(self.NMesh, dtype = np.float32)[None, :, None]
                  + self.rfn[None, None, :])
        self.k_ind = ((self.fn[:, None, None]**2.
                  + self.fn[None, :, None]**2.
                  + self.rfn[None, None, :]**2.)**(0.5)).astype(np.float32)
        # Fundamental Frequency and Nyquist Frequency
        self.Kf = 2*np.pi/self.BoxSize
        self.Knyq = np.pi*self.NMesh/self.BoxSize
        
    def ReadCat(self, CatPATH):
        """
        Read dark matter particle catalog
        """
        self.Position = np.zeros([1,3])
        
        for i in range(4):
            print(i)
            filename = CatPATH + '/snap_0.6250_PtcleDensity_Ng512/00000' + str(i) + '.hdf5'
            f = h5py.File(filename, "r")
            Position = f['/PartType1']['/PartType1/Coordinates']
            self.Size += Position.shape[0]
            self.Position = np.vstack((self.Position,Position))
        self.Position = self.Position[1:, :]
        
        # Duplicate original position data
        self.Position0 = self.Position

    def Readfof(self, CatPATH):
        """
        Read from fof data file
        """
        f = open(CatPATH)
        content = f.readlines()
        self.Size = len(content)
        self.Position = np.zeros([self.Size, 3])
        
        for i in range(self.Size):
            self.Position[i, :] = content[i].split()[0:3]
        
        self.Position *= self.BoxSize
        
    def Readsnapshots(self, snapPATH):
        """
        Read the snapshots generated by Gadget
        """
        snapshot = snapPATH
        ptype   = [1] 
        self.Position = readgadget.read_block(snapshot, "POS ", ptype)/1e3
        self.Size = self.Position.shape[0]
        self.Position = self.Position.astype(np.float32)
        self.Position0 = np.array(self.Position)
        